// 更新全局数据
export const UPDATE_GLOBAL_DATA = 'UPDATE_GLOBAL_DATA';

// 更新弹窗数据
export const UPDATE_POPUP_DATA = 'UPDATE_POPUP_DATA';

// 设置弹窗数据
export const SET_POPUP_DATA = 'SET_POPUP_DATA';

// 更新实名数据
export const UPDATE_REAL_NAME_DATA = 'UPDATE_REAL_NAME_DATA';

// 获取实名信息
export const FETCH_REAL_NAME_BEGIN = 'FETCH_REAL_NAME_BEGIN';
export const FETCH_REAL_NAME_SUCCESS = 'FETCH_REAL_NAME_SUCCESS';
export const FETCH_REAL_NAME_FAILURE = 'FETCH_REAL_NAME_FAILURE';

// 认证实名信息
export const SUBMIT_REAL_NAME_BEGIN = 'SUBMIT_REAL_NAME_BEGIN';
export const SUBMIT_REAL_NAME_SUCCESS = 'SUBMIT_REAL_NAME_SUCCESS';
export const SUBMIT_REAL_NAME_FAILURE = 'SUBMIT_REAL_NAME_FAILURE';
